### ISSUE TITLE
Can not find `react-stylename` module at npmjs.com

### ISSUE THREAD

**Issue by giiska** [texttechne/react-stylename#2]

**Comment by texttechne** [comment]
yep. I'm not convinced of the used approach, so I haven't released it to npm yet.
I'm still thinking about solving this...

**Comment by cavaloni** [comment]
This would be a wonderful release because it bypasses all of the difficulty with jest testing and using webpack compilations for stylename only. Hope you keep it up!

**Comment by texttechne** [comment]
I think this is solved now by: https://github.com/gajus/babel-plugin-react-css-modules

@cavaloni: Any reason to use this lib instead?
